#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
#mybatis:
#  mapper-locations:classpath:mappers/*xml

#指定Mybatis的实体目录
#mybatis:type-aliases-package:
#  com.wanwan.springboot.mybatis.entity
# 应用服务 WEB 访问端口
server:
  ip : localhost
#  ip : 120.79.148.126
  port: 9090

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${server.ip}:3306/wanwan?serverTimezone=GMT%2b8
    username: root
    password: root
  mvc:
    pathmatch:
      # 整合swagger时报错解决
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  #扫描所有xml文件
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    打印日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
#    path: /home/files/
    path: D:/IdeaProjects/小白做毕设2024/files/
