#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
#mybatis:
#  mapper-locations:classpath:mappers/*xml

#指定Mybatis的实体目录
#mybatis:type-aliases-package:
#  com.wanwan.springboot.mybatis.entity
# 应用服务 WEB 访问端口
server:
  port: 8080

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanwan?serverTimezone=GMT%2b8
    username: root
    password: root
  mvc:
    pathmatch:
      # 整合swagger时报错解决
      matching-strategy: ant_path_matcher
mybatis:
  #扫描所有xml文件
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    打印日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl